"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ku_as45vs5isd^px=t#m8g#^*x7f=w#gw-xb^t@^-pom)r^t6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS for development and production: include backend API, localhost, container hostname, and frontend origins.
ALLOWED_HOSTS = [
    '.kavia.ai',  # prod domain
    'localhost',
    '127.0.0.1',
    'testserver',
    # Allow front-end IP/hostname if using external React dev server:
    'vscode-internal-0002-beta.beta01.cloud.kavia.ai',
    # Allow Docker container hostnames if using docker-compose integration
    'backend',  # internal hostname (edit as appropriate)
]

# Explicitly declare CSRF trusted origins for frontend-backend integration and for AJAX POSTs from frontend
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://vscode-internal-0002-beta.beta01.cloud.kavia.ai:3000",
    # Add your production front-end domain here
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'api'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Handles CORS first!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# [Container Coordination]
# For cross-container compatibility, SQLite DB path is read from the SQLITE_DB environment variable if set,
# otherwise falls back to local 'db.sqlite3'.
# To initialize the DB and apply migrations, run:
#     python manage.py makemigrations
#     python manage.py migrate
# To create a superuser for Django admin, run:
#     python manage.py createsuperuser

import os

SQLITE_DB_PATH = os.environ.get('SQLITE_DB')
if SQLITE_DB_PATH:
    DB_LOCATION = SQLITE_DB_PATH
else:
    DB_LOCATION = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_LOCATION,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration for React frontend-backend integration
CORS_ALLOW_ALL_ORIGINS = False  # Only allow specified client origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Local React dev
    "http://127.0.0.1:3000",
    "https://vscode-internal-0002-beta.beta01.cloud.kavia.ai:3000",
    # Add production frontend URL(s) here
]
CORS_ALLOW_CREDENTIALS = True    # Allow sending of cookies (for session, auth)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_EXPOSE_HEADERS = [
    'Content-Type',
    'X-CSRFToken',
    'Set-Cookie',
]
CORS_PREFLIGHT_MAX_AGE = 86400  # Reduce number of preflight requests

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Django session and cookie settings for cross-origin security and React
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7    # 1 week sessions
SESSION_SAVE_EVERY_REQUEST = True        # Update expiry on activity

SESSION_COOKIE_SECURE = False  # Set True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Can be 'Strict', 'Lax', or 'None' (use 'None' if frontend served on different domain w/ https)

CSRF_COOKIE_SECURE = False  # Set True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # If you want JS to read it for fetch()
CSRF_COOKIE_SAMESITE = 'Lax'  # 'Lax' for most safe React AJAX interop
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Use default authentication
]

# Set custom User model if used (already in models.py)
AUTH_USER_MODEL = 'api.User'

# REST Framework auth configuration for session + cookie-based login/logout
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        # You could add JWT or TokenAuthentication for non-cookie use.
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'UNAUTHENTICATED_USER': None,
    'UNAUTHENTICATED_TOKEN': None,
}
